language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'

jobs:
  fast_finish: true
  allow_failures:
    - php: 7.1

install:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/coverage.xml

after_script:
  - vendor/bin/coveralls -v --coverage_clover build/logs/coverage.xml
